### PR TITLE
Remove TestTokenAwareConnPool

### PR DESCRIPTION
**Pull request by martin-sucha**
This test only works with Cassandra, not Scylla because of different
ConnPool implementation. The test is also missing verification that
the query went to the correct host, so it's of questionable value.
We run tests against Scylla, so removing the test to fix CI.

### CODE REVIEW

**Comment by mrVanboy** [comment]
Is there any chance to determine which DB is used in tests and rather do [`t.Skipf`](https://pkg.go.dev/testing#T.Skipf) instead of removing it? I concerned about the divergence between our fork and upstream.

**Comment by martin-sucha** [comment]
> Is there any chance to determine which DB is used in tests

We could test the type of `connPicker` inside `hostConnPool` inside `policyConnPool` after the first connection has connected. A bit complicated IMO.

> and rather do t.Skipf instead of removing it? I concerned about the divergence between our fork and upstream.

We could do t.Skipf() always, as we are running tests only against Scylla if you prefer that.

**Comment by martin-sucha** [comment]
Ok, created alternate pull request: https://github.com/kiwicom/gocql/pull/18

**Comment by martin-sucha** [comment]
Closed in favour of https://github.com/kiwicom/gocql/pull/18

**Pull request closed without merging**
